name: API CI

#on: [push]
on:
  push:
    paths:
      - "./src/demos/src/api**"
      - "./src/demos/src/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./src/demos/src/api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: ./src/demos/package-lock.json
      - name : installing dependencies
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm run test
